package share;
/*
Author: Ziqi Tan
*/
public enum RequestHead {
	LOGIN,
	LOGOUT,
	GET_STUDENT_LIST,
	GET_COURSE_LIST,
	GET_CATEGORY_LIST,
	GET_ASSIGNMENT_LIST,
	GET_SUBMISSION_LIST,

	ADD_INSTRUCTOR,
	ADD_STUDENT,
	DROP_STUDENT,
	WITHDRAW_STUDENT,

	SELECT_COURSE,

	ADD_COURSE,
	ADD_CATEGORY,
	ADD_ASSIGNMENT,
	ADD_SUBMISSION,

	DELETE_COURSE,
	DELETE_CATEGORY,
	DELETE_ASSIGNMENT,
	DELETE_SUBMISSION,
	UPDATE_STUDENT,
	UPDATE_COURSE,
	UPDATE_CATEGORY,
	UPDATE_ASSIGNMENT,
	UPDATE_SUBMISSION,

	CHECK_COURSE_VALID, // Check if the sum of weights of all categories is 100%
	CHECK_CATEGORY_VALID  // Check if the sum of weights of all submissions is 100%
}
