package share;
/*
Author: Ziqi Tan
*/
public enum RequestHead {
	LOGIN,
	LOGOUT,
	GET_STUDENT_LIST,
	GET_COURSE_LIST,
	GET_CATEGORY_LIST,
	GET_ASSIGNMENT_LIST,
	GET_SUBMISSION_LIST,
	ADD_STUDENT,
	ADD_COURSE,
	ADD_CATEGORY,
	ADD_ASSIGNMENT,
	ADD_SUBMISSION,
	REMOVE_STUDENT,
	REMOVE_COURSE,
	REMOVE_CATEGORY,
	REMOVE_ASSIGNMENT,
	REMOVE_SUBMISSION,
	UPDATE_STUDENT,
	UPDATE_COURSE,
	UPDATE_CATEGORY,
	UPDATE_ASSIGNMENT,
	UPDATE_SUBMISSION,
	
	SELECT_COURSE

}
